name: "develop"

concurrency: "develop"

on:
  push:
    branches:
      - develop
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  code-scanning:
    uses: ./.github/workflows/reusable-codeql-analysis.yml

  unit-tests:
    uses: ./.github/workflows/reusable-unit-tests.yml
    with:
      disable-coverage-archival: ${{ github.event_name == 'schedule' }}

  api-library-tests:
    uses: ./.github/workflows/reusable-api-library-tests.yml
    with:
      disable-coverage-archival: ${{ github.event_name == 'schedule' }}

  package-tests:
    uses: ./.github/workflows/reusable-package-tests.yml

  integration-tests-on-prem:
    uses: ./.github/workflows/reusable-integration-tests-on-prem.yml
    with:
      disable-coverage-archival: ${{ github.event_name == 'schedule' }}
