name: "Pull Request Labeler"

on:
  pull_request_target:
    branches:
      - develop

jobs:
  label:
    if: ${{ !startsWith(github.event.pull_request.head.ref, 'renovate/') }}

    runs-on: ubuntu-latest

    steps:
      - uses: srvaroa/labeler@1eec6d9e7c5fa5864840279978680302f955fc37 # v1.10.1
        env:
          GITHUB_TOKEN: ${{ secrets.EFEBIA_TEAM_TOKEN }}
